# Generated by Django 6.1 on 2026-09-09 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_cliente_options_cliente_keycloak_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medio', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('BILLETERA', 'Billetera Digital / Móvil'), ('TARJETA', 'Tarjeta Débito / Crédito'), ('EFECTIVO', 'Efectivo / Caja'), ('OTRO', 'Otro')], default='TRANSFERENCIA', help_text='Clasificación del instrumento de pago.', max_length=20, verbose_name='Tipo de Medio')),
                ('entidad_bancaria', models.CharField(help_text='Nombre de la entidad bancaria o proveedora (ej. Banco Itaú, Continental, Tigo Money, etc.).', max_length=100, verbose_name='Entidad Bancaria / Billetera')),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta bancaria o número telefónico asignado a la billetera digital.', max_length=50, verbose_name='Número de Cuenta / Teléfono')),
                ('titular', models.CharField(help_text='Nombre completo o razón social del titular del medio de pago.', max_length=150, verbose_name='Titular de la Cuenta / Billetera')),
                ('documento_titular', models.CharField(blank=True, help_text='Cédula de identidad civil o RUC del titular del medio de pago (opcional).', max_length=30, verbose_name='Documento / RUC del Titular')),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Indica si este es el medio de pago seleccionado por defecto para liquidaciones.', verbose_name='Predeterminado')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el medio de pago se encuentra habilitado para operar.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de registro.', verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última actualización.', verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(help_text='Cliente titular al cual pertenece este medio de pago.', on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='customers.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['-es_predeterminado', '-created_at'],
                'indexes': [models.Index(fields=['cliente', 'activo'], name='payments_pa_cliente_e375be_idx'), models.Index(fields=['cliente', 'es_predeterminado'], name='payments_pa_cliente_210c29_idx')],
            },
        ),
    ]
