# Generated by Django 6.1 on 2026-09-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_anio_vencimiento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año de vencimiento de la tarjeta (formato AAAA, 4 dígitos).', null=True, verbose_name='Año de Vencimiento'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_mes_vencimiento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mes de vencimiento de la tarjeta (1-12).', null=True, verbose_name='Mes de Vencimiento'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarjeta_ultimos_digitos',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos visibles de la tarjeta. El resto del número nunca se almacena.', max_length=4, verbose_name='Últimos 4 Dígitos'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='telefono_billetera',
            field=models.CharField(blank=True, help_text='Número de teléfono asociado a la billetera móvil (formato validado en clean()).', max_length=20, verbose_name='Teléfono de Billetera'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tipo_cuenta_bancaria',
            field=models.CharField(blank=True, choices=[('AHORRO', 'Caja de Ahorro'), ('CORRIENTE', 'Cuenta Corriente')], help_text='Clasificación de la cuenta para transferencias bancarias.', max_length=20, verbose_name='Tipo de Cuenta Bancaria'),
        ),
    ]
