# Generated by Django 6.1 on 2026-09-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_tarjeta_anio_vencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del banco o proveedor de billetera.', max_length=100, unique=True, verbose_name='Nombre de la Entidad')),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('BILLETERA', 'Billetera Digital')], help_text='Clasifica si es un banco o una billetera digital.', max_length=20, verbose_name='Tipo de Entidad')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la entidad está disponible para selección en los formularios.', verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Define la prioridad de aparición en los dropdowns (menor valor aparece primero).', verbose_name='Orden de Aparición')),
            ],
            options={
                'verbose_name': 'Entidad Financiera',
                'verbose_name_plural': 'Entidades Financieras',
                'ordering': ['tipo', 'orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='entidad_bancaria',
            field=models.ForeignKey(help_text='Entidad seleccionada del catálogo parametrizado.', on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='payments.entidadfinanciera', verbose_name='Entidad Bancaria / Billetera'),
        ),
    ]
