# Generated by Django 6.1 on 2026-09-20 01:56

from django.db import migrations


def crear_catalogo_inicial(apps, schema_editor):
    EntidadFinanciera = apps.get_model('payments', 'EntidadFinanciera')
    bancos = ['Banco Itaú', 'Banco Continental', 'BNF', 'Banco GNB', 'Banco Basa',
              'Banco Sudameris', 'Banco Ueno']
    billeteras = ['Tigo Money', 'Personal', 'Wally', 'Zimple']
    for i, nombre in enumerate(bancos):
        EntidadFinanciera.objects.create(nombre=nombre, tipo='BANCO', orden=i)
    for i, nombre in enumerate(billeteras):
        EntidadFinanciera.objects.create(nombre=nombre, tipo='BILLETERA', orden=i)


class Migration(migrations.Migration):
    dependencies = [('payments', '0003_add_entidad_financiera')]
    operations = [migrations.RunPython(crear_catalogo_inicial, migrations.RunPython.noop)]
