# Generated by Django 6.1 on 2026-09-20 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_seed_entidades_financieras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='entidad_bancaria',
            field=models.ForeignKey(blank=True, help_text='Entidad seleccionada del catálogo parametrizado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='payments.entidadfinanciera', verbose_name='Entidad Bancaria / Billetera'),
        ),
    ]
