# Generated by Django 6.1 on 2026-09-22 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_cliente_usuario_customeruserassignment_and_more'),
        ('payments', '0005_entidad_bancaria_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'Caja de Ahorro'), ('CORRIENTE', 'Cuenta Corriente'), ('BILLETERA', 'Billetera Digital / Móvil')], help_text='Clasificación de la cuenta destino para acreditación.', max_length=20, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta bancaria o teléfono de billetera destino.', max_length=50, verbose_name='Número de Cuenta / Teléfono')),
                ('titular', models.CharField(help_text='Nombre completo o razón social del titular de la cuenta receptora.', max_length=150, verbose_name='Titular de la Cuenta')),
                ('documento_titular', models.CharField(blank=True, help_text='Cédula de identidad o RUC del titular (opcional).', max_length=30, verbose_name='Documento / RUC del Titular')),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Indica si esta es la cuenta preferida para recibir acreditaciones.', verbose_name='Predeterminado')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la cuenta está habilitada (borrado lógico).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(help_text='Cliente titular de esta cuenta de acreditación de fondos.', on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='customers.cliente', verbose_name='Cliente')),
                ('entidad_bancaria', models.ForeignKey(help_text='Entidad seleccionada del catálogo parametrizado.', on_delete=django.db.models.deletion.PROTECT, related_name='medios_acreditacion', to='payments.entidadfinanciera', verbose_name='Entidad Bancaria / Billetera')),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
                'ordering': ['-es_predeterminado', '-created_at'],
                'indexes': [models.Index(fields=['cliente', 'activo'], name='payments_re_cliente_941770_idx'), models.Index(fields=['cliente', 'es_predeterminado'], name='payments_re_cliente_3d9ae3_idx')],
            },
        ),
    ]
