# Generated by Django 6.1 on 2026-10-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_cliente_usuario_customeruserassignment_and_more'),
        ('payments', '0006_add_receiving_method'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Identificador único emitido por la pasarela (ej. evt_...).', max_length=255, unique=True, verbose_name='ID de Evento')),
                ('gateway', models.CharField(default='STRIPE', help_text='Pasarela de origen del webhook.', max_length=20, verbose_name='Pasarela')),
                ('tipo_evento', models.CharField(help_text='Clasificación del evento notificado (ej. payment_intent.succeeded).', max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(default=dict, help_text='Cuerpo completo recibido en la petición del webhook.', verbose_name='Carga Útil JSON')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si la lógica de negocio correspondiente ya fue ejecutada.', verbose_name='Procesado')),
                ('error_mensaje', models.TextField(blank=True, help_text='Detalle de error si ocurrió una excepción durante el procesamiento.', verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Procesamiento')),
            ],
            options={
                'verbose_name': 'Evento de Webhook de Pago',
                'verbose_name_plural': 'Eventos de Webhooks de Pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe Checkout / Cards'), ('SIPAP', 'Transferencia Bancaria SIPAP')], default='STRIPE', help_text='Proveedor o pasarela tecnológica utilizada para el cobro.', max_length=20, verbose_name='Pasarela de Pago')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Identificador único de la sesión de Stripe Checkout (cs_test_...).', max_length=255, null=True, verbose_name='ID de Sesión (Checkout)')),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, help_text='Identificador del PaymentIntent asociado en Stripe (pi_...).', max_length=255, null=True, verbose_name='ID de PaymentIntent')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto cobrado o a procesar a través de la pasarela.', max_digits=18, verbose_name='Monto de Operación')),
                ('moneda', models.CharField(default='USD', help_text='Código de moneda de la operación en la pasarela (ej. USD, PYG).', max_length=10, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('COMPLETADO', 'Completado / Pagado'), ('FALLIDO', 'Fallido / Rechazado'), ('CANCELADO', 'Cancelado / Expirado'), ('REEMBOLSADO', 'Reembolsado')], db_index=True, default='PENDIENTE', help_text='Estado actual del cobro en la pasarela externa.', max_length=20, verbose_name='Estado del Pago')),
                ('checkout_url', models.URLField(blank=True, help_text='URL de redirección al formulario seguro hospedado por Stripe.', max_length=500, null=True, verbose_name='URL de Stripe Checkout')),
                ('referencia_externa', models.CharField(blank=True, help_text='Código de referencia o ID devuelto por el proveedor de pago.', max_length=255, verbose_name='Referencia Externa')),
                ('datos_evento', models.JSONField(blank=True, default=dict, help_text='Carga útil o metadatos JSON suministrados por la pasarela.', verbose_name='Datos de Evento / Metadatos')),
                ('error_mensaje', models.TextField(blank=True, help_text='Detalle o causa del fallo si la transacción no pudo completarse.', verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente titular al cual pertenece esta operación de pasarela.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_records', to='customers.cliente', verbose_name='Cliente')),
                ('transaction', models.ForeignKey(blank=True, help_text='Transacción de cambio asociada a este intento de pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_records', to='transactions.transaction', verbose_name='Transacción Cambiaria')),
            ],
            options={
                'verbose_name': 'Registro de Pasarela de Pago',
                'verbose_name_plural': 'Registros de Pasarela de Pago',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='payments_pa_session_bad246_idx'), models.Index(fields=['payment_intent_id'], name='payments_pa_payment_b929cd_idx'), models.Index(fields=['gateway', 'estado'], name='payments_pa_gateway_62d01b_idx')],
            },
        ),
    ]
