# Generated by Django 6.1 on 2026-10-08 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentwebhookevent_paymentgatewayrecord'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipapTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transferencia', models.CharField(db_index=True, help_text='Número de comprobante o referencia interbancaria única (ej. SIPAP-20261008-001234).', max_length=64, unique=True, verbose_name='Código de Transferencia SIPAP')),
                ('banco_origen', models.CharField(help_text='Entidad bancaria desde la cual se remitieron los fondos.', max_length=100, verbose_name='Banco / Entidad de Origen')),
                ('cuenta_origen', models.CharField(help_text='Número de cuenta bancaria del cliente remitente.', max_length=50, verbose_name='Cuenta de Origen')),
                ('titular_origen', models.CharField(help_text='Nombre completo o razón social del titular remitente.', max_length=150, verbose_name='Titular de Origen')),
                ('documento_origen', models.CharField(blank=True, help_text='Documento de identidad o RUC del titular remitente.', max_length=30, verbose_name='Documento / RUC de Origen')),
                ('banco_destino', models.CharField(default='Banco Itaú Paraguay', help_text='Entidad bancaria recaudadora de Global Exchange.', max_length=100, verbose_name='Banco de Destino')),
                ('cuenta_destino', models.CharField(default='900-1234567-01', help_text='Número de cuenta recaudadora oficial.', max_length=50, verbose_name='Cuenta de Destino')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto exacto transferido en la operación SIPAP.', max_digits=18, verbose_name='Monto Transferido')),
                ('moneda', models.CharField(default='PYG', help_text='Código de moneda de la transferencia (ej. PYG, USD).', max_length=10, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Conciliación'), ('CONFIRMADA', 'Confirmada / Acreditada'), ('RECHAZADA', 'Rechazada'), ('REVERTIDA', 'Revertida')], db_index=True, default='PENDIENTE', help_text='Estado actual de la conciliación bancaria.', max_length=20, verbose_name='Estado de la Transferencia')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Razón documentada en caso de no poder conciliar la transferencia.', verbose_name='Motivo de Rechazo')),
                ('fecha_transferencia', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp informado por la entidad bancaria.', verbose_name='Fecha de Transferencia')),
                ('fecha_conciliacion', models.DateTimeField(blank=True, help_text='Timestamp en que el sistema confirmó el depósito.', null=True, verbose_name='Fecha de Conciliación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información complementaria devuelta por la red SIPAP.', verbose_name='Metadatos SIPAP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('gateway_record', models.ForeignKey(blank=True, help_text='Registro general de pasarela de pago vinculado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sipap_transfers', to='payments.paymentgatewayrecord', verbose_name='Registro de Pasarela')),
                ('transaction', models.ForeignKey(blank=True, help_text='Transacción asociada para liquidación automática.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sipap_transfers', to='transactions.transaction', verbose_name='Transacción Cambiaria')),
            ],
            options={
                'verbose_name': 'Registro de Transferencia SIPAP',
                'verbose_name_plural': 'Registros de Transferencias SIPAP',
                'ordering': ['-fecha_transferencia'],
                'indexes': [models.Index(fields=['codigo_transferencia'], name='payments_si_codigo__1d5d49_idx'), models.Index(fields=['estado', 'fecha_transferencia'], name='payments_si_estado_dc570e_idx')],
            },
        ),
    ]
