# Generated by Django 6.1 on 2026-09-10 20:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código alfabético de 3 letras mayúsculas de la moneda (ej. USD, PYG, EUR).', max_length=3, unique=True, verbose_name='Código ISO 4217')),
                ('name', models.CharField(help_text='Nombre completo descriptivo de la moneda (ej. Dólar Estadounidense, Guaraní Paraguayo).', max_length=50, verbose_name='Nombre de la Moneda')),
                ('symbol', models.CharField(help_text='Símbolo representativo de la divisa (ej. $, ₲, €, R$, £).', max_length=10, verbose_name='Símbolo')),
                ('decimals', models.PositiveSmallIntegerField(default=2, help_text='Cantidad de cifras decimales admitidas para la moneda (0 para PYG, 2 para USD/EUR).', verbose_name='Decimales')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la moneda está disponible para operaciones de cambio y cotizaciones.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de registro de la moneda.', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación de los datos de la moneda.', verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SegmentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('MIN', 'Minorista'), ('MAY', 'Mayorista'), ('COR', 'Corporativo'), ('VIP', 'VIP')], db_index=True, help_text='Categoría o segmento de clientes al cual se le aplican estas condiciones tarifarias.', max_length=3, unique=True, verbose_name='Segmento de Cliente')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión sobre el monto total de la operación (0.00% a 100.00%).', max_digits=5, verbose_name='Porcentaje de Comisión (%)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión fija aplicable por transacción independiente del volumen operado.', max_digits=12, verbose_name='Cargo Fijo por Operación')),
                ('spread_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de bonificación o reducción del margen de spread para este segmento (0.00% a 100.00%).', max_digits=5, verbose_name='Descuento sobre Spread (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta política de comisión se encuentra actualmente en vigencia.', verbose_name='Regla Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de inserción de la regla.', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de la última modificación de los parámetros de comisión.', verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Comisión por Segmento',
                'verbose_name_plural': 'Comisiones por Segmento',
                'ordering': ['segment'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=6, help_text='Precio de compra de la divisa base expresado en unidades de la moneda destino.', max_digits=18, verbose_name='Tasa de Compra')),
                ('sell_rate', models.DecimalField(decimal_places=6, help_text='Precio de venta de la divisa base expresado en unidades de la moneda destino.', max_digits=18, verbose_name='Tasa de Venta')),
                ('spread', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), editable=False, help_text='Diferencial calculado automáticamente como margen entre venta y compra (sell_rate - buy_rate).', max_digits=18, verbose_name='Spread Cambiario')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento exacto a partir del cual rige esta cotización.', verbose_name='Vigente Desde')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Momento en el que expira la cotización (opcional, null si permanece vigente hasta nuevo aviso).', null=True, verbose_name='Vigente Hasta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la tasa está habilitada actualmente para cotizaciones y transacciones.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de inserción en el sistema.', verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Última Actualización')),
                ('base_currency', models.ForeignKey(help_text='Moneda que se toma como unidad de referencia para la cotización (ej. USD en USD/PYG).', on_delete=django.db.models.deletion.PROTECT, related_name='base_exchange_rates', to='rates.currency', verbose_name='Moneda Base (Origen)')),
                ('target_currency', models.ForeignKey(help_text='Moneda en la que se expresa el precio de la unidad base (ej. PYG en USD/PYG).', on_delete=django.db.models.deletion.PROTECT, related_name='target_exchange_rates', to='rates.currency', verbose_name='Moneda Destino (Cotizada)')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Operador o administrador responsable de la fijación de la cotización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exchange_rates', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-valid_from', '-created_at'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency', 'is_active', '-valid_from'], name='rates_excha_base_cu_e32753_idx')],
            },
        ),
    ]
