# Generated by Django 6.1 on 2026-09-20 17:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('MIN', 'Minorista'), ('MAY', 'Mayorista'), ('COR', 'Corporativo'), ('VIP', 'VIP')], db_index=True, help_text='Categoría o segmento comercial de clientes al cual se aplican estos límites.', max_length=3, verbose_name='Segmento de Cliente')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto mínimo requerido por transacción individual en esta divisa.', max_digits=18, verbose_name='Monto Mínimo por Operación')),
                ('monto_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto tope permitido por transacción individual (0.00 = sin límite individual).', max_digits=18, verbose_name='Monto Máximo por Operación')),
                ('limite_diario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto máximo acumulado habilitado en un día calendario (0.00 = sin límite diario).', max_digits=18, verbose_name='Límite Acumulado Diario')),
                ('limite_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto máximo acumulado habilitado en un mes calendario (0.00 = sin límite mensual).', max_digits=18, verbose_name='Límite Acumulado Mensual')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta política de límites se encuentra actualmente en vigencia.', verbose_name='Regla Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de inserción de la regla.', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de la última modificación de los parámetros de límites.', verbose_name='Última Actualización')),
                ('currency', models.ForeignKey(help_text='Divisa sobre la cual rigen los límites monetarios parametrizados.', on_delete=django.db.models.deletion.CASCADE, related_name='operation_limits', to='rates.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Límite Operativo',
                'verbose_name_plural': 'Límites Operativos',
                'ordering': ['segment', 'currency__code'],
                'constraints': [models.UniqueConstraint(fields=('segment', 'currency'), name='unique_segment_currency_operation_limit')],
            },
        ),
    ]
