# Generated by Django 6.1 on 2026-10-09 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_cliente_usuario_customeruserassignment_and_more'),
        ('rates', '0002_operationlimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], help_text='Operación de compra o venta cuya tasa se desea vigilar.', max_length=4, verbose_name='Tipo de Operación')),
                ('tasa_umbral', models.DecimalField(decimal_places=6, help_text='Valor de la tasa contra el cual se evalúa la condición de la alerta.', max_digits=18, verbose_name='Tasa Umbral')),
                ('condicion', models.CharField(choices=[('GTE', 'Mayor o igual que'), ('LTE', 'Menor o igual que')], help_text='Comparación que debe cumplir la tasa respecto del umbral.', max_length=3, verbose_name='Condición')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la suscripción está vigente y debe ser evaluada.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación de la suscripción.', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Última Actualización')),
                ('base_currency', models.ForeignKey(help_text='Moneda base del par vigilado (ej. USD en USD/PYG).', on_delete=django.db.models.deletion.PROTECT, related_name='base_rate_alerts', to='rates.currency', verbose_name='Moneda Base')),
                ('cliente', models.ForeignKey(help_text='Cliente titular de la suscripción de alerta.', on_delete=django.db.models.deletion.CASCADE, related_name='rate_alerts', to='customers.cliente', verbose_name='Cliente')),
                ('target_currency', models.ForeignKey(help_text='Moneda cotizada del par vigilado (ej. PYG en USD/PYG).', on_delete=django.db.models.deletion.PROTECT, related_name='target_rate_alerts', to='rates.currency', verbose_name='Moneda Destino')),
            ],
            options={
                'verbose_name': 'Suscripción de Alerta de Cotización',
                'verbose_name_plural': 'Suscripciones de Alertas de Cotización',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', 'activo'], name='rates_ratea_cliente_60dd2a_idx'), models.Index(fields=['base_currency', 'target_currency', 'activo'], name='rates_ratea_base_cu_c00c20_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve de la notificación.', max_length=150, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Contenido completo de la notificación.', verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el usuario ya leyó la notificación.', verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de generación de la notificación.', verbose_name='Fecha de Creación')),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación.', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Usuario',
                'verbose_name_plural': 'Notificaciones de Usuario',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leido'], name='rates_usern_usuario_ce8e32_idx')],
            },
        ),
    ]
