# Generated by Django 6.1 on 2026-09-23 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_cliente_usuario_customeruserassignment_and_more'),
        ('payments', '0006_add_receiving_method'),
        ('rates', '0002_operationlimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(blank=True, db_index=True, help_text='Identificador único correlativo de la transacción (ej. TX-20260923-00001).', max_length=32, unique=True, verbose_name='Código de Referencia')),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra de Divisas'), ('VENTA', 'Venta de Divisas')], default='COMPRA', help_text='Indica si se trata de una compra o venta de divisas.', max_length=10, verbose_name='Tipo de Operación')),
                ('tasa_base', models.DecimalField(decimal_places=6, help_text='Tasa oficial de mercado (compra o venta) fijada al momento de la transacción.', max_digits=18, verbose_name='Tasa Base Oficial')),
                ('comision_segmento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de comisión deducido o cobrado según el segmento comercial.', max_digits=18, verbose_name='Comisión de Segmento')),
                ('tasa_neta', models.DecimalField(decimal_places=6, help_text='Tasa efectiva final aplicada tras aplicar bonificaciones de spread y comisiones.', max_digits=18, verbose_name='Tasa Neta Aplicada')),
                ('monto_origen', models.DecimalField(decimal_places=2, help_text='Monto bruto entregado por el cliente en moneda de origen.', max_digits=18, verbose_name='Monto de Origen')),
                ('monto_destino', models.DecimalField(decimal_places=2, help_text='Monto neto recibido o a liquidar en moneda de destino.', max_digits=18, verbose_name='Monto de Destino')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('COMPLETADA', 'Completada / Liquidada'), ('CANCELADA', 'Cancelada / Expirada')], db_index=True, default='PENDIENTE', help_text='Estado del ciclo de vida de la orden cambiaria.', max_length=15, verbose_name='Estado de la Transacción')),
                ('token_congelamiento', models.CharField(blank=True, db_index=True, help_text='Token único de la cotización congelada en sesión si aplica (ej. QTZ-XXXXXXXX).', max_length=64, null=True, verbose_name='Token de Congelamiento')),
                ('observaciones', models.TextField(blank=True, help_text='Notas o comentarios adicionales relativos a la transacción.', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp automático de registro de la transacción.', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Última Actualización')),
                ('base_currency', models.ForeignKey(help_text='Moneda base o divisa extranjera de referencia del par (ej. USD).', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_base', to='rates.currency', verbose_name='Moneda Base')),
                ('cliente', models.ForeignKey(help_text='Cliente titular de la transacción cambiaria.', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='customers.cliente', verbose_name='Cliente')),
                ('exchange_rate', models.ForeignKey(blank=True, help_text='Registro de tasa de cambio oficial de referencia al momento de la orden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='rates.exchangerate', verbose_name='Cotización Aplicada')),
                ('medio_acreditacion_destino', models.ForeignKey(help_text='Cuenta receptora seleccionada para recibir los fondos liquidados.', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_acreditacion', to='payments.receivingmethod', verbose_name='Medio de Acreditación de Destino')),
                ('medio_pago_origen', models.ForeignKey(help_text='Instrumento con el cual el cliente paga los fondos.', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_pago', to='payments.paymentmethod', verbose_name='Medio de Pago de Origen')),
                ('target_currency', models.ForeignKey(help_text='Moneda en la que se cotiza la unidad base (ej. PYG).', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_target', to='rates.currency', verbose_name='Moneda Destino (Cotizada)')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario del sistema o cajero que registró o gestionó la operación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Operador')),
            ],
            options={
                'verbose_name': 'Transacción Cambiaria',
                'verbose_name_plural': 'Transacciones Cambiarias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', 'estado', '-created_at'], name='transaction_cliente_cad2ec_idx'), models.Index(fields=['tipo_operacion', 'estado'], name='transaction_tipo_op_4f8325_idx'), models.Index(fields=['codigo_referencia'], name='transaction_codigo__ce2666_idx')],
            },
        ),
    ]
