# Generated by Django 6.1 on 2026-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp exacto en que se confirmó y acreditó el pago de la orden (SCRUM-94).', null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pasarela_pago',
            field=models.CharField(blank=True, help_text='Pasarela tecnológica utilizada para el pago (STRIPE, SIPAP, EFECTIVO).', max_length=20, verbose_name='Pasarela de Pago'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='referencia_externa_pago',
            field=models.CharField(blank=True, db_index=True, help_text='Código de referencia o ID de cobro devuelto por la pasarela (Stripe, SIPAP, etc.).', max_length=255, verbose_name='Referencia Externa de Pago'),
        ),
    ]
